GET http://localhost:3000/api/movies

###

POST http://localhost:3000/api/users/login
Content-Type: application/json

    {    
    "first_name" : "asfas",
    "last_name" : "asfas",
    "email" : "asfas@asfas.com",
    "username" : "asfas",
    "password" : "1!qQazxsw"
    }

### 

GET http://localhost:3000/api/dbtest
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXNmYXNAYXNmYXMuY29tIiwiaWF0IjoxNzM1ODA4MjY4fQ.n0X-xbP6AOtGV0kSkQLJ2BByr6lrZhrHvEjckrB0Ur8

