GET http://localhost:3000/api/movies

###

POST http://localhost:3000/api/users/login
Content-Type: application/json

    {    
    "first_name" : "asfas",
    "last_name" : "asfas",
    "email" : "asfas@asfas.com",
    "username" : "asfas",
    "password" : "1!qQazxsw"
    }

### 

GET http://localhost:3000/api/dbtest

{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsInJvbGUiOiJ1c2VyIiwidXNlcm5hbWUiOiJqb25hcyIsInBhc3N3b3JkIjoiYXNmYXNhc2ZhcyIsImlhdCI6MTczNTkxOTA4NX0.0mGts_Meo_JrYlBjbbqCQc3F3oSvI985v5N-tKSUDis"}
